### ISSUE TITLE
Question regarding Detect menus & videos

### ISSUE THREAD

**Issue by ke5koB** [rj200/Glamarye_Fast_Effects_for_ReShade#1]
Hello, Robert!
First of all, thank you very much!
Your shader immediately became a must have for me from the very first release.
I'm wondering  if it's possible to make a standalone version of Detect menus & videos, that will work with other shaders as well?
For example,can we have two instances "Detect menus & videos Start.fx" and "Detect menus & videos End.fx" and all shaders between them will be disabled or enabled depending on the depth buffer?

**Comment by rj200** [comment]
Yes. Actually quite simple. Here you go:

https://raw.githubusercontent.com/rj200/Glamarye_Fast_Effects_for_ReShade/main/Shaders/Detect_menus_and_videos_wrapper.fx

**Comment by ke5koB** [comment]
Thanks a lot again!This is exactly what I was looking for! 
btw Latest update with redused AO in bright areas is just amazing.
