### ISSUE TITLE
About your shader and some request

### ISSUE THREAD

**Issue by sanek7814** [rj200/Glamarye_Fast_Effects_for_ReShade#11]
At the moment I firmly assert that your sharpening filter is the best one available, even better than CAS by amd and Nvidia sharpen, which I understood after a lot of testing and comparing your shader with others.  I would like to know when there will be new versions? Plus I have an idea about Contrast Adaptive Sharpen. I'll be glad if I get an answer.

**Comment by rj200** [comment]
Thank you, It's the result of lots of thought and experimentation so I appreciate the positive feedback.

I was working on an update (mostly Fake GI tweaking) in the autumn but it's not quite ready and I've been a bit distracted by replaying The Witcher 3 recently.

**Comment by sanek7814** [comment]
I appreciate the work done to achieve such a result, but I have some ideas how to improve your sharpness, I will now take the example with nvidia sharpen, the point is that the sharpness does not go to all of the image that is not 100%, objects in the distance do not change their sharpness. I tested it in Saints Row 4, in case of CAS the sharpness was increased on all objects, in case of nvidia sharpen objects in the distance, did not change their sharpness. As I think this is done to prevent artifacts on small objects.

**Comment by sanek7814** [comment]
https://i.ibb.co/PZWKFJh/image.jpg  Link to the screenshot where this is clearly shown.
The blue cross is those places that change their sharpness, the red cross is those places that do not change sharpness.
You can check it yourself, on my github there is this shader called nvidia sharpen.

**Comment by rj200** [comment]
Actually, if depth is available, then the "subtle depth of field" option in Glamayre controls this. If you disable it it sharpens everything equally, if it's enabled but a low strength then sharpen effect decreases with distance. If high strength DoF then distant objects will also be blurred a little.

**Comment by sanek7814** [comment]
I didn't know about it, or was constantly disabling it, thanks for the clarification.
