### ISSUE TITLE
Detect Menu doesn't work in Hogwarts Legacy.

### ISSUE THREAD

**Issue by Silenbt** [rj200/Glamarye_Fast_Effects_for_ReShade#15]
I tried both "Detect menus & videos" and "Detect sky", but AO still through menu and video cutscene.

**Comment by rj200** [comment]
It depend on the game. It uses the depth buffer, and it assumes the game sets depth to 0 for menus and 1 for sky. 

Lots of games don't do that unfortunately - there's not anything I can do about it.

**Comment by Silenbt** [comment]
Ok, thank you.
