### ISSUE TITLE
Not compatible with Reshade 5.9.0

### ISSUE THREAD

**Issue by adamnorbacker** [rj200/Glamarye_Fast_Effects_for_ReShade#18]
Does not compile with Reshade >5.9.0
Fails to resolve AddressU

**Comment by flaunt5** [comment]
#19 should address this

**Comment by GT500org** [comment]
> #19 should address this

Thanks. That seems to have fixed the issue for me.

**Comment by Aztec2012** [comment]
> #19 should address this

Dont understand what to do to fix?

**Comment by Aztec2012** [comment]
> > #19 should address this
> 
> Dont understand what to do to fix?

Nevermind. Fix work, Thanks.

**Comment by Aztec2012** [comment]
> #19 should address this

But it makes very blurry.

**Comment by Aztec2012** [comment]
Just delete :
AddressU = BORDER;
AddressV = BORDER;
AddressW = BORDER;

in lines 1115-1117 and 1124-1127

This fix and not blurry i mean.

**Comment by rj200** [comment]
6.4.2 released with [Aztec2012](https://github.com/Aztec2012)'s fix.
