### ISSUE TITLE
rj_sharpen failed to compile

### ISSUE THREAD

**Issue by Aztec2012** [rj200/Glamarye_Fast_Effects_for_ReShade#7]
rj_sharpen failed to compile on Reshade 5.2.2

**Comment by Aztec2012** [comment]
Glamayre_Fast_Effects.fx too.

**Comment by rj200** [comment]
Can you find the error message in the logs tab so I can see where it failed?

Also, it requires ReShade.fxh from the default ReShade shader repository that normally gets installed unless you unselect it. Check you have it [(https://github.com/crosire/reshade-shaders)](https://github.com/crosire/reshade-shaders/tree/slim/Shaders)

**Comment by Aztec2012** [comment]
Yes i have ReShade.fxh. Here is log
[ReShade.log](https://github.com/rj200/Glamarye_Fast_Effects_for_ReShade/files/9127639/ReShade.log)

**Comment by Aztec2012** [comment]
On new 5.3.0 version the same error.

**Comment by Aztec2012** [comment]
Strange. Glamayre_Fast_Effects.fx from main Github page has 800 kb size and 10496 total lines, Glamayre_Fast_Effects.fx from releases has only 100 kb size and 1885 total lines. So from releases works fine. Thnaks nad sorry,

**Comment by rj200** [comment]
I think you downloaded the github web page about the file instead of the file itself - use either releases, or the raw button to just get one file in github.
